### PR TITLE
#233 action to change application to changes required [Action]

### LINKED ISSUE #233: action to change application to changes requested
### NOTE
This won't require any changes to code, just configuration, check this PR: https://github.com/openmsupply/application-manager-server/pull/238

part of epic https://github.com/openmsupply/application-manager-web-app/issues/94

When review of last level is submitted to LOQ, we want to change application to changes_requested status.

currently have these action with the following configurations:

change status of application to submitted (on submit)

```
 {
                actionCode: "changeStatus"
                trigger: ON_APPLICATION_SUBMIT
                sequence: 1
                parameterQueries: {
                  applicationId: {
                    operator: "objectProperties"
                    children: ["applicationData.applicationId"]
                  }
                  newStatus: { value: "Submitted" }
                }
              }
```

change status of review to submitted on submit

```
 {
                actionCode: "changeStatus"
                trigger: ON_REVIEW_SUBMIT
                sequence: 2
                parameterQueries: {
                  reviewId: {
                    operator: "objectProperties"
                    children: ["applicationData.record_id"]
                  }
                  newStatus: { value: "Submitted" }
                }
              }
```

would envision that action (and parameters it gets on submission), is slightly extended to do this:

```
 {
                actionCode: "changeStatus"
                trigger: ON_REVIEW_SUBMIT
                sequence: 3
                condition: {
                        operator: "="
                        children: [
                          {
                            operator: "objectProperties"
                            children: ["reviewData.reviewDecision.decision"]
                          }
                          { value: "List Of Questions" }
                        ]
                      }
                parameterQueries: {
                  applicationId: {
                    operator: "objectProperties"
                    children: ["applicationData.applicationId"]
                  }
                  reviewId: {
                    operator: "objectProperties"
                    children: ["applicationData.record_id"]
                  }
                  newApplicationStatus: { value: "Changes Requested" }
                }
              }
```

`newApplicationStatus` <- this determines which record to set (application or id)
-> `children: ["reviewData.reviewDecision.decision"]` exposed for conditioning

### PR DESCRIPTION
**Pull request by andreievg**
Fixes #233
Branched from #232 

### Changes

Config only changes, to use similar condition as updateReviewVisibility (on submit, when decision is LOQ and last review level)

### Testing

Can use this mutation and query afterwards (also console logs of server):

```
mutation MyMutation {
  __typename
  updateReview(
    input: {
      patch: {
        trigger: ON_REVIEW_SUBMIT
        reviewDecisionsUsingId: { create: { decision: LIST_OF_QUESTIONS } }
        reviewResponsesUsingId: {
          updateById: [
            {
              patch: {
                recommendedApplicantVisibility: ORIGINAL_RESPONSE_VISIBLE_TO_APPLICANT
              }
              id: 38
            }
            {
              patch: {
                recommendedApplicantVisibility: ORIGINAL_RESPONSE_VISIBLE_TO_APPLICANT
              }
              id: 37
            }
          ]
        }
      }
      id: 6
    }
  ) {
    review {
      applicationId
    }
  }
}

query MyQuery {
  __typename
  application(id: 4002) {
    status
    name
  }
}

```

### CODE REVIEW

**Review by CarlosNZ — CHANGES_REQUESTED** [review]
Cool, can you update this to integrate with the new coreActions file?

**Comment by andreievg** [comment]
@CarlosNZ 
> Cool, can you update this to integrate with the new coreActions file?

I've merged from master then after conflict resolution (which involved deleting core action template), added new action config to core actions.hs

**Comment by andreievg** [comment]
@CarlosNZ can you please look at the changes

**Review by CarlosNZ — APPROVED** [review]

**Comment by CarlosNZ** [comment]
> @CarlosNZ can you please look at the changes

Sorry, forgot about this. Yeah LGTM now.

**Pull request merged**
