### PR TITLE
#594 Export / Import localisation and prefs with snapshots

### LINKED ISSUE #594: Config files -- export with snapshots
I realise that it's currently not easy to change anything in the configuration file(s) (such as default language), as it's part of the build.

Would be good if config files (from front and back end) were (optionally) exported with snapshots, so they could be edited separately, then re-imported. (A snapshot could be ONLY a config file, in some cases).

Similarly, would it make sense to just have a single config file, rather then separate front and back end ones?

Why don't we just put the config file in back-end, and have the front-end "require" it remotely?

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #594 

- Additional options parameters to specify if "localisation" folder and "preferences" should be exported/imported with snapshot
- Update use/take snapshot scripts to export/import them
- Add base localisations and prefs to "basic_snapshot"

So we'll need to remember that when we want to change language settings or prefs, to update them in "basic_snapshot", not in the project root, as they'll be overwritten next time "basic_snapshot" is loaded. (Unless we intentionally *exclude* them from basic_snapshot so the project root versions are the "master" versions? -- what do you think is best?)

### CODE REVIEW

**Comment by nmadruga** [comment]
> * Additional options parameters to specify if "localisation" folder and "preferences" should be exported/imported with snapshot

Very nice. I was missing that definetelly!

**Comment by nmadruga** [comment]
> So we'll need to remember that when we want to change language settings or prefs, to update them in "basic_snapshot", not in the project root, as they'll be overwritten next time "basic_snapshot" is loaded. (Unless we intentionally _exclude_ them from basic_snapshot so the project root versions are the "master" versions? -- what do you think is best?)

I think something like this needs to be documented in the wiki somewhere. Maybe in the document where we talk about snapshots (the one that needs updating)

**Comment by CarlosNZ** [comment]
> I think something like this needs to be documented in the wiki somewhere. Maybe in the document where we talk about snapshots (the one that needs updating)

Sure, but which option do you prefer?

**Review by nmadruga — APPROVED** [review]
Looks good. I can see the files beiing exported and imported correctly.
I'll try another one without exporting those to see how it imports, but so far so good.

I just have one sort of unrelated question.

The languagesFile imported looks like this:
Screen Shot 2021-10-05 at 3 24 22 PM

But when II go select the language is giving me 2 options:
Screen Shot 2021-10-05 at 3 24 03 PM
Screen Shot 2021-10-05 at 3 23 46 PM

**Comment by CarlosNZ** [comment]
> But when II go select the language is giving me 2 options:
Screen Shot 2021-10-05 at 3 27 24 PM

😉

**Comment by nmadruga** [comment]
Cool. Thanks! All looks good to me

**Pull request merged**
