### PR TITLE
522-snapshot-to-work-when-importing-completed-application

### PR DESCRIPTION
**Pull request by andreievg**
Fixes: #522 
update for trigger vs insert, merged to demo already.

@CarlosNZ, I think we need to also do a condition of OLD.outcome = 'PENDING" ?

### CODE REVIEW

**Comment by CarlosNZ** [comment]
> @CarlosNZ, I think we need to also do a condition of OLD.outcome = 'PENDING" ?

Yeah, I guess, although once applications are "COMPLETED" (i.e. Outcome <> "Pending"), they should never change again. But feel free to add it.

**Comment by andreievg** [comment]
I've added that check, I am surprised that there are no duplicates, since there is also an update after to change trigger to null

**Comment by CarlosNZ** [comment]
> I am surprised that there are no duplicates, since there is also an update after to change trigger to null

I'm pretty sure I checked that when I updated it originally -- both functions have no overlap in their condition fields, so it should be all good.

**Review by CarlosNZ — APPROVED** [review]
Great, thanks.

**Comment by nmadruga** [comment]
Can we merge this up @andreievg?

Was hoping we could do this today:

`main` would get PRs: #523, #521
`develop` should get changes from master + PRs #513, #524 & #528

**Comment by andreievg** [comment]
rebased, no conflicts.

**Pull request merged**
