### PR TITLE
#326 Fix to allow result of GraphQL operation to return Null instead of fallback

### LINKED ISSUE #326: Allow returning null from result of GraphQL query in Expression evaluator

### PR DESCRIPTION
**Pull request by nmadruga**
Fixes #326 

Another quick fix, needed to get proper result for when the query results on `null` as "no results" for the given input.

### CODE REVIEW

**Comment by CarlosNZ** [comment]
Cool, but needs test cases for it. Just add one more test using the query you're planning to use in the Drug reg template.

**Comment by nmadruga** [comment]
Ah! I just realised that now haha. Will do that in a minute

**Comment by nmadruga** [comment]
Hi @CarlosNZ it is still failing on one test: "Test unresolved object with Null fallback" which I'm not sure what to do about it
```
testData.objectPropertyUnresolvedWithNullFallback = {
  operator: 'objectProperties',
  children: ['application.querstions.q2', null],
}
```

**Review by CarlosNZ — CHANGES_REQUESTED** [review]
🙁
Screen Shot 2021-04-29 at 1 03 01 PM

**Comment by nmadruga** [comment]
> 🙁
> Screen Shot 2021-04-29 at 1 03 01 PM

Please see comment above ^

**Review by CarlosNZ — APPROVED** [review]
Great -- thanks!

Once you merge this, publish it and then bump the version number directly on master to save doing another PR.

**Comment by nmadruga** [comment]
> Great -- thanks!
> 
> Once you merge this, publish it and then bump the version number directly on master to save doing another PR.

Ok. Thanks! I'll probably need to create one for Front-end, or should just do straight on master as well?

**Comment by CarlosNZ** [comment]
> Ok. Thanks! I'll probably need to create one for Front-end, or should just do straight on master as well?

Yeah, you're literally just changing the minimum version number in `package.json`, (and re-run `yarn` so `yarn.lock` updates too).

**Pull request merged**
