### PR TITLE
#479F Long text plugin

### PR DESCRIPTION
**Pull request by CarlosNZ**
Update Feature Showcase template to include a couple of LongText element plugins. To use with [front-end PR #555](https://github.com/openmsupply/application-manager-web-app/pull/555)

### CODE REVIEW

**Review by nmadruga — APPROVED** [review]
LGTM

I was wondering if we should start removing those `id` fields from each question now that we don't use that anymore - since we have Assignment in place. But you decide if it's worth or not doing that (for Feature showcase only) as part of this PR.

**Comment by CarlosNZ** [comment]
> I was wondering if we should start removing those `id` fields from each question now that we don't use that anymore - since we have Assignment in place. But you decide if it's worth or not doing that (for Feature showcase only) as part of this PR.

Yeah, we should, but I'd rather do it in a more systematic way than trying to squeeze it in here, cos there might be unintended consequences that make it more complicated than we think.

**Comment by nmadruga** [comment]
> Yeah, we should, but I'd rather do it in a more systematic way than trying to squeeze it in here, cos there might be unintended consequences that make it more complicated than we think.

Sure. No problem. Then probably just need to add a issue related to the current Epic - so we don't forget about this?

**Comment by CarlosNZ** [comment]
> Then probably just need to add a issue related to the current Epic - so we don't forget about this?

Okay, made an issue for "final tidy-ups": https://github.com/openmsupply/application-manager-web-app/issues/583

Feel free to add to it if you think of anything

**Comment by nmadruga** [comment]
Thanks!

**Review by nmadruga — APPROVED** [review]

**Pull request merged**
