### PR TITLE
312 Snapshot improvements

### PR DESCRIPTION
**Pull request by andreievg**
Fixes: #312 

I juggled some files around, thus the big diff

Existing snapshot wont' work with this PR

Application data can now be exported via `--profile applicationData`, allowing template config changes to be made via `insertData/` and retaining snapshot application/review data

### Changes

* Added git ignore to snapshots/ folder (to make sure it's committed)
* Further documentation based on changes and requests in #312
* Relocated shared scripts to `database/helpers`, no `insertData` and `updateRowPolicies` scripts both just call methods in helpers, which also means `--from-insert-data` parameter can be removed when invoking them
* `insertCoreData` takes option 'ignoreFiles' parameter (defaults to [])
* relocating snapshot scripts to `database/snapshotScripts` and definitions (not `profiles`) to `database/snapshotProfiles`
* added new `applicationData` profile (for review and applicationData)
* made `takeSnapshot` and `useSnapshot` export methods (can be used in code and test now quite easily)
* `snaphost.js` is used to call `takeSnapshot` and `useSnapshot`, it takes command line parameters (described in documentation) it's also used in packages json for `take_snapshot` and `use_snapshot` scripts
* added file snapshoting
* generated columns are not required in definitions anymore (added view->GraphQL query) for that purpose
* timestamps are exported by default

### CODE REVIEW

**Comment by CarlosNZ** [comment]
Looks good. About to give it a proper test.

One thing though -- the "name" parameter doesn't seem to work in conjunction with the `--profile` parameter. If I do:
`yarn take_snapshot myNewSnapshot --profile applicationData`
it just makes a "current" snapshot and ignores the name. Name works okay if I don't use `--profile`

**Comment by CarlosNZ** [comment]
I'm getting this error (sometimes) when exporting snapshot:
```
prettifying mutations ...
[error] database/snapshots/current/mutation.graphql: SyntaxError: Syntax Error: Expected Name, found Int "0". (1856:169)
[error]   1854 | 
[error]   1855 | ########### applicationResponse 16 ###########
[error] > 1856 | mutation { createApplicationResponse(input: {applicationResponse: {id:16,templateElementId:1022,applicationId:1,status:DRAFT,value:{text:"*<Nothing Selected>*",values:{0:{text:"Tick me",selected:false}}},isValid:true,timeUpdated:"2021-04-27T12:09:44.811814+12:00"}}){clientMutationId}}
[error]        |                                                                                                                                                                         ^
[error]   1857 | ########### MUTATION END ###########
[error]   1858 | 
[error]   1859 | ########### applicationResponse 17 ###########
(node:11503) UnhandledPromiseRejectionWarning: Error: Command failed: npx prettier --write "database/snapshots/current"
[error] database/snapshots/current/mutation.graphql: SyntaxError: Syntax Error: Expected Name, found Int "0". (1856:169)
[error]   1854 | 
```

It seems to be only related to prettier, so the actual export appears okay, it just doesn't get formatted.

Here is the snapshot if you want to try it out:
[current.zip](https://github.com/openmsupply/application-manager-server/files/6381058/current.zip)

**Comment by CarlosNZ** [comment]
One thing that might be useful for debugging purposes is if you can get the script to output the whole mutation (or line number) that failed.
I just tried to export then re-import a snapshot using "applicationData" profile and got the following error:
```
[
  {
    "message": "Syntax Error: Expected Name, found Int \"0\"",
    "locations": [
      {
        "line": 4,
        "column": 169
      }
    ]
  }
]
```
The line/column reference in there is just relative to the current mutation, not the source file, so it's not straightforward to try and figure out where the problem mutation is.

**Comment by andreievg** [comment]
> Looks good. About to give it a proper test.

> One thing though -- the "name" parameter doesn't seem to work in conjunction with the --profile parameter. If I do:
yarn take_snapshot myNewSnapshot --profile applicationData
it just makes a "current" snapshot and ignores the name. Name works okay if I don't use --profile

> Edit: The "name" seems to be ignored if used in conjunction with any of the other parameters.

I've made name to be last parameter (it seemed easier to figure it out), although I am not that experienced with passing through arguments/parameters to command line

**Comment by andreievg** [comment]
> One thing that might be useful for debugging purposes is if you can get the script to output the whole mutation (or line number) that failed.
> I just tried to export then re-import a snapshot using "applicationData" profile and got the following error:

Looks like it was exiting before chance to log:  42f414c69d1728630608fb4430ab1f88486cef88

Should we log query in executeGraphQLQuery (regardless of where it's called from ?)

**Comment by andreievg** [comment]
> I'm getting this error (sometimes) when exporting snapshot:

ok after a bit of digging, it turns out it's the checkbox, we storing: `values:{0:{text:"Tick me",selected:true}}}`, which prettier can't deal with (numbered keys), I've tried quoting numbered keys, and still no luck. I am not sure if it's a valid JSON.

Anyways this is an example fix for front end: https://github.com/openmsupply/application-manager-web-app/compare/example-key-as-number-fix

Do you think it would break anything ?

**Comment by nmadruga** [comment]
Can this one be merged? It would be very handy to have it on master for use. I tried using the one in master but is borken.

**Comment by andreievg** [comment]
@nmadruga 
> Can this one be merged? It would be very handy to have it on master for use. I tried using the one in master but is borken.

I am going to make a PR today from demo with more additions to snapshotting, hopefully today

**Comment by andreievg** [comment]
closing in favour of snapshot2.0

**Pull request closed without merging**
