### PR TITLE
#381F Updating Review assignments for ReviewTest applications

### PR DESCRIPTION
**Pull request by nmadruga**
To be used for [Front-end PR#381](https://github.com/openmsupply/application-manager-web-app/pull/452)

### Changes
- Fix one question assigned to INFORMATION element
- Fix for question assignment ids
- Commenting Review assignment so it's easier the mock data for current reviews in progress/submitted
- Added one Review (For reviewer 2, Application 34567) as **Locked**

### CODE REVIEW

**Review by andreievg — APPROVED** [review]
looks good to me.

just one thing to note, we've added `recommended_applicant_visibility` and `is_visible_to_applicant`, the former is set by front end and the later by back end on review submission. <- they determine what is visible to applicant during LOQ. I've been testing this functionality with new reviews. Just want to note, that with existing reviews this might not work as expdcted

**Comment by nmadruga** [comment]
> just one thing to note, we've added recommended_applicant_visibility and is_visible_to_applicant, the former is set by front end and the later by back end on review submission. <- they determine what is visible to applicant during LOQ. I've been testing this functionality with new reviews. Just want to note, that with existing reviews this might not work as expected

Thanks for noting that, I haven't consider that on the submissions, although none of these are going back to applicant yet! Just from used for these 3 examples:
1. Application 12345: Stage 1 (Approved), Stage 2 lvl 1 (S1 Approved, S2 Declined) and waiting for one of Consolidators to start
2. Application 23456: Stage 1 (Assigned) waiting for Reviewer 1 to start. No lvl 2 assignment yet...
3. Application 34567: Stage 1 (Approved), Stage 2 lvl 1 (S1 Declined, S2 in Draft), lvl 2 Consolidator (Disagree with review lvl 1) => Changes Requested to Reviewer 1 (S1 Declined), Locked for Reviewer 2 (S2 Locked)

**Comment by andreievg** [comment]
> I haven't added review_decision though, I'm not sure if any of these cases would have a review_decision, maybe for the Stage 1 completed reviews?

I think every iteration of application review should have a decision (it also serves as a comment), by default would be `NO_DECISION`. I think review create creates one now

**Comment by nmadruga** [comment]
> I think every iteration of application review should have a decision (it also serves as a comment), by default would be NO_DECISION. I think review create creates one now

Cool. I'll add to each Review on this PR before merging then : )

**Comment by andreievg** [comment]
> Cool. I'll add to each Review on this PR before merging then : )

Thanks Nicle

**Pull request merged**
